### Retrieve Tasks
GET {{baseUrl}}/v1/tasks

### Create Tasks
POST {{baseUrl}}/v1/tasks
Content-Type: application/json

{
    "title":"New Task",
    "description": "Close backend"
}

### Update Task
PATCH {{baseUrl}}/v1/tasks/0EYaCRAVwkJNnz3kcfTs
Content-Type: application/json

{
    "title": "Updated Title Task"
}

### Delete Task
DELETE {{baseUrl}}/v1/tasks/0EYaCRAVwkJNnz3kcfTs
